### ISSUE TITLE
目標管理サイトをどうするか

### ISSUE THREAD

**Issue by machidyo** [MATLABJINDAI/yourwholelife#2]
目標管理サイトをどんな風に作るか考えよう！
## 技術的な話

| 項目 | 種類 | 備考 |
| :-: | :-: | :-: |
| 言語 | C# |  |
| 環境 | Azure WebSite |  |
| DB | 使わない |  |
| CSS Framework | Bootstrap |  |
## 役割

| 役 | ID |
| :-: | :-: |
| プロジェクトリーダー | machidyo |
| メンバー | ZazenWorks |

**Comment by machidyo** [comment]
いくつかしつもーん :jack_o_lantern: 
- Windows じゃないと C# が使いにくいわ、そういや、すっかり忘れてた。
- Bootstrap 使っていい？前のサイトでも使ってたんだけど、それっぽくなるから。最近の流行りだし。
- 軽くやるなら DB なしで Azure の無料じゃダメ？

**Comment by machidyo** [comment]
ジャックランタンのカード思い出した。。。

**Comment by ZazenWorks** [comment]
回答
- Windowsじゃないとってのはサーバが？開発環境が？
- Bootstrapとか全然いいよ。
- DBなしで目標管理できるならいいよ。

前にも書いたと思うけど、俺は目標管理のイメージが出来てないから
基本的に細かいところはお前主導で決めちゃっていいよ、DBなしでとかBootstrap使うとか。
言語とかは影響でかいところは一応提案て形で相談にしようよ？

**Comment by ZazenWorks** [comment]
ジャックランタン？前やってたゲームの？全然思い出せない。

**Comment by machidyo** [comment]
回答
- サーバが Windows じゃないと、.NET 使うのがちょっとめんどい
- Bootstrap で
- DB なしで

**Comment by machidyo** [comment]
目標管理というか、目標共有ぐらい、イメージとしては。去年の劣化盤でいいかなって気がしている。
- ログイン画面　→　担当ぜんちゃん
- 目標の羅列画面　→　担当おれ

とりあえずこれだけでいっかなって思ってるんだけど。

**Comment by machidyo** [comment]
言語は目標管理は C# でいくって合意していたつもりだったんだけど、何か他がいい？

**Comment by machidyo** [comment]
ジャックランタンじゃなかったっけ？ヴァルハラゲートに出てきた魔法系のキャラ。

**Comment by ZazenWorks** [comment]
・AzureだとサーバWindowsなのか？
・DBなしだと目標登録とかはテキストファイルに保存する？
・目標羅列画面だけってことは表示するだけ？それだとログインいらなくない？

言語はC＃でいいよ

ジャックランタンいた気はするけど、どんな絵だったか思い出せない。
てかそもそもどこから出てきたんだ？w

**Comment by machidyo** [comment]
・Azure だとサーバは選べる。無料で使える Web サイトだけ使うと OS は意識しないかな。
・テキストファイルに保存する。
・ログインぐらいあってもいっかなと思ってみたり。もうちょっと機能足してもいいし。最初は Light で。

:jack_o_lantern:　←　ジャックランタンね。

**Comment by ZazenWorks** [comment]
OK。
で、どうやって進めてく？
画面デザインとか、仕様とか？
まーログイン画面くらいならテキトーに作れるけど、
これからを見越して進め方は決めたいね。

かぼちゃなのはわかるw

**Comment by machidyo** [comment]
画面デザインとかなんか作ってもいい気もするけど、
その一方で組んじゃってもいいんじゃねって気もする。
なかなか構築に入れないし（笑）
なんか案あったらそれにのっかるけど。

**Comment by ZazenWorks** [comment]
そうそう。なかなか進まないよなwお前平日忙しそうだし。
ここでの会話なかなか進まないからLINEかHangOutとかのメッセージアプリで
やりとりした方が早いんじゃない？

基本は言い出しっぺがリードしていくのがいいでしょ。
例えば目標管理はマッチーがリーダー。俺（メンバー）は意見だすけどまとめるのはマッチー。
スケジュール管理は俺がリーダー。マッチーは意見してまとめるのは俺。

俺はリーダー経験ないからやるときは探り探りになるけど
なんかやり方知ってるなら、経験あるなら教えて欲しい。

**Comment by machidyo** [comment]
そして遅くなってすいません。。。
んじゃ、俺まとめでいきましょか。
とりあえず目標管理作り始めよか。

**Comment by machidyo** [comment]
VisualStudio2013 インストールしておいて。
俺はデプロイする Azure サイト準備するわ。

**Comment by ZazenWorks** [comment]
MacにVisualStudioインストールできないっぽいんだけど、
XamarinってやつでC＃できるからそれでいいよね？

**Comment by machidyo** [comment]
C# ビルドできればいいけど、VisualStuido 使ったほうが better だね。インテリセンスとか考えても開発効率がぜんぜん違うと思うし。Mac しかないんだっけ？

**Comment by ZazenWorks** [comment]
マックしかないよ。VSインストールするにはWindowsが必要みたいだね。じゃとりあえずビルドはできるだろうからXamarinってのでやってみるよ

**Comment by machidyo** [comment]
あんまりよくわかってないが、よろしく頼むわ！とりあえず C# ビルドできるようになったら教えて。こちらも Azure の準備しますわ。

**Comment by ZazenWorks** [comment]
オK。あと、俺の方がこれに時間さけるだろうから、なんかやることが見えてるなら
がんがん一週間じゃやりきれないくらいの指示だして。とりあえずビルド環境整えるわ。

**Comment by machidyo** [comment]
やれそうだったら
- 可能なら Azure のアカウントとってもらえると助かるかな
- ビルド環境整えたら
  - ソリューション作る
  - GitHub にコミットする
  - ログイン画面作る
    - MVC(ver5.0) で作る
    - Bootstrap(ver3.0) で作る

かな。

**Comment by ZazenWorks** [comment]
残念なお知らせ。Xamarinお高いらしい。実質Macで無料でC#は無理っぽい。
どうしようか？

Azureのアカウント作ろうとしたけど職場の電話番号が必須で、
俺のいる職場の電話は派遣先の出行先で電話番号は私用で登録とかきついです。

総合的に俺C#きついのかな。やってみたいんだけどな

**Comment by machidyo** [comment]
あははは、んじゃ C# やめよっか、いまさらだけど。どう？

**Comment by machidyo** [comment]
スケジュール管理、やってみっか？言語どうする？前に話してた JavaScript とか？

**Comment by machidyo** [comment]
Amazon の無料で Linux のなんか上げて、そこで適当にやるか。

**Comment by ZazenWorks** [comment]
C＃はとりあえず諦めた方が良さそうかな。
別に作るのは目標管理でいいけど。言語はJSでやってみようか。
Amazonの無料のまだできるの？

**Comment by machidyo** [comment]
Amaznon の無料できないけど、メールアドレスかなにかで Sign up するだけなら、新しいメアドで・・・。

JS でいきましょか！

**Comment by machidyo** [comment]
目標管理からスケジュール管理に変えようと思ったのは、ぜんのほうが時間ありそうだったから、リードしてもらえたら楽かなって思って。

**Comment by ZazenWorks** [comment]
アマゾンの無料のはクレカの登録があるから２回目は無理だと思うよ。
じゃー
言語：JS
リーダー：俺
作るもの：とりあえずスケジュール管理

問題：サーバがない。
解決案：借りる？

他に解決案があればあげて。
なければサーバを探そう。
IaaSがいいかな？

**Comment by machidyo** [comment]
Heroku どう？これは PaaS だけど、なんら問題ないと思うんだよね。有料っぽく書いてあるけど、[これ](http://codezine.jp/article/detail/8344)読むと1アプリケーションは無料そう。

**Comment by machidyo** [comment]
早く書きたいね～って意味でも PaaS は楽でいいかも。 そのほか、言語、リーダー、作るもの、了解。

**Comment by ZazenWorks** [comment]
> Herokuでは1つのアプリケーションにつき750Dyno Hourの無料枠があるからです。
> サーバーを稼働させてる時間なのかログインしてる時間も含まれるのかわからないけど
> そんなに使わなければ無料っぽいね。今週できたら他のPaaS調べてみるわ。

**Comment by ZazenWorks** [comment]
http://pivotal.io/platform-as-a-service/pivotal-cloud-foundry

MEAN STACKで始めるならCloud foundryが良さそう。
MongoDBとNode.jsが必要だから。
どうやって始めるかわからないけどw

**Comment by ZazenWorks** [comment]
https://www.openshift.com/
https://www.dotcloud.com/
http://cloudcontrol.com/
こっちもMongoとNodeは使えそう。

herokuはnode使えるけどMongoが使えなさそう。
ま、MEANにこだわらなくてもいいんだけどね。

**Comment by ZazenWorks** [comment]
dotCloudは無料枠なくなったみたい

**Comment by ZazenWorks** [comment]
http://run.pivotal.io/
一番上のはここらしいけど６０日だけっぽいな。
openshiftが３アプリ無料、cloudcontrolは多分１ヶ月分動作させるの無料（herokuと同じっぽい）
だからとりあえずopenshiftにしてみようか。

**Comment by ZazenWorks** [comment]
openshiftはteamsってのが有料じゃないと含まれてないらしい。teamsってのがなんなのか分からんけど、cloudcontrolで行けそうならそっちにするか

**Comment by ZazenWorks** [comment]
どっちがいいのか、どの機能が使えるのか、細かいところがどっちもよくわからないな。

**Comment by ZazenWorks** [comment]
http://nodejs-jmatlab.rhcloud.com/

**Comment by machidyo** [comment]
> No credit card required

これ、ちょっとウケるな。みんなネックに思ってんだな。

**Comment by machidyo** [comment]
openshift がいいんじゃねって思った、 Red Hat だし。とりあえず temas はなしでもいけるだろ、よくわからんしw

**Comment by machidyo** [comment]
早くコード書きたいわ～。ちょっと Jenkins とかもやりたいって思い出してきた。夢ばかり膨らむ。こういう時間が一番楽しいのかもww

**Comment by ZazenWorks** [comment]
とりあえずopenshiftで作ってみた
DB追加とか、jenkinsも追加できるけど、追加するごとに１GEAR追加になるから
多分１GEAR追加になって２GEAR以上になると金がかかる

**Comment by ZazenWorks** [comment]
GITとは連携できそう

**Comment by machidyo** [comment]
1 GEAR って単位がすげーな。
Git 連携できるのはいいね、Jenkins いるのかな。
とりあえずテストでデプロイして適当なアプリ動かしてみたいね。

**Comment by ZazenWorks** [comment]
ちなみに
http://www.publickey1.jp/blog/11/paas2011.html
ここを参考にした

**Comment by ZazenWorks** [comment]
あ、３GEARまで使えるみたい。だからDBとJenkinsも追加できるな。
もしくは３つWebアプリ作れるってことだな。

**Comment by ZazenWorks** [comment]
できればJenkins使って運用して、アジャイルに近い感じで開発していきたい。そういうプロジェクトの初めから終わりまでやりきる練習みたいな感じになればと勝手に思ってる。まー練習じゃなくて本番になれば最高だけどな。

**Comment by machidyo** [comment]
そだね。とは言え、先にプログラミングできたほうがいい気がする。Jenkins とかやりだすと環境作るのに時間かかるだろうから、アプリ作りながら考えたほうがいいかなと。
（明日早いから、今日は寝るわ、すまね。）

**Comment by ZazenWorks** [comment]
あんま関係ないけどUnityがアップデートして便利になったみたいだな

**Comment by ZazenWorks** [comment]
gitインストールするのに色々インストールしないといけなかったり環境作りもなかなか大変だな。英語が多いし。

**Comment by machidyo** [comment]
Unity 便利になったみたいね～ちょっと心がそっちに揺らぐわ・・・。

> 環境作りもなかなか大変だな。英語が多いし。

環境構築に時間かけるよりとりあえず作りながらでいいとも思う。どう？

**Comment by ZazenWorks** [comment]
作れる状態にする環境構築してる。と思う。よくわからないこと多いし

**Comment by machidyo** [comment]
なるほど。大変ご苦労様です。分担できそうならやろうと思うのだけど、どう？

**Comment by ZazenWorks** [comment]
分担できるならしたいけど、できるかどうかもようわからんwできなさそうだけど。
とりあえず、OpenShiftと俺のマックをつなげて開発できるようにしてる。
https://developers.openshift.com/en/getting-started-osx.html
このページの「Setting up Your Machine」
のはじめの方。

で、ギットと連携できたらマッチーはギットに上げて、俺がソースまとめて
OpenShiftにアップロードって流れかな？って思ってるけど、どうだか？w

**Comment by ZazenWorks** [comment]
http://trymean-jmatlab.rhcloud.com/#!/
これを改造していく感じっぽい。
とりあえず、今日は終了するわ。

**Comment by machidyo** [comment]
とりあえずこの issue 閉じて、新しいのにしようか。
